### ISSUE TITLE
This is awesome! 

### ISSUE THREAD

**Issue by feross** [dominictarr/varstruct#1]
Neat idea for a module! This might help simplify my module [bittorrent-tracker](https://github.com/feross/bittorrent-tracker/). In order to talk to a UDP tracker, you have to produce some packed binary data (like a C struct) and I'm doing it by hand now. See: https://github.com/feross/bittorrent-tracker/blob/master/index.js#L261

When I implement UDP tracker servers (which I haven't done yet) I might give varstruct a try and see how it goes since that will involve a lot of unpacking.

**Comment by fanatid** [comment]
@feross do you still interesting in using `varstruct` in `bittorrent-tracker`?

**Comment by feross** [comment]
@fanatid I already implemented UDP tracker support without using `varstruct`, but if you think it would clean things up, I would accept a PR. Don't have time to play with this myself, right now!

**Comment by fanatid** [comment]
I've posted PR with `varstruct` to `bittorrent-tracker`: https://github.com/feross/bittorrent-tracker/pull/136
