### ISSUE TITLE
Magic/value type

### ISSUE THREAD

**Issue by dcousens** [dominictarr/varstruct#10]
It'd be great if you could do something like:

``` js
vstruct([
  { type: vstruct.value(0xdeadbeef) },
  { name: 'data', type: vstruct.Buffer(32) }
])
```

You'd need to encode the type though I suppose,  so maybe:

``` js
vstruct([
  { type: vstruct.UInt32, value: 0xdeadbeef },
  { name: 'data', type: vstruct.Buffer(32) }
])
```

**Comment by dcousens** [comment]
You should link to https://github.com/dominictarr/varstruct-match in the README... I decided to use this instead :+1:

**Comment by fanatid** [comment]
Yes, maybe we do, but this package mentioned in https://github.com/mafintosh/abstract-encoding

**Comment by dcousens** [comment]
Actually, this would still be useful to have.

**Comment by dcousens** [comment]
Also,  @fanatid what would be the best way to do a checksum... using `Bound`?

**Comment by dcousens** [comment]
Alternative proposed syntax:

``` js
vstruct.value(vstruct.UInt32LE, 0xdeadbeef)
```

**Comment by dcousens** [comment]
Closing in favour of https://github.com/dominictarr/varstruct/pull/16

**Comment by fanatid** [comment]
Re checksum: yes, I think `Bound` is the best here
