### ISSUE TITLE
Safe Buffer (from, alloc, etc)

### ISSUE THREAD

**Issue by dcousens** [dominictarr/varstruct#12]
This module isn't compliant at the moment,  might submit a PR if/when I have the time

**Comment by fanatid** [comment]
agree, @dcousens don't worry about it, I'll do

**Comment by dominictarr** [comment]
can you link to something on what "safe buffer" means?

**Comment by fanatid** [comment]
@dominictarr I think @dcousens says about this: https://nodejs.org/api/buffer.html#buffer_what_makes_buffer_allocunsafe_and_buffer_allocunsafeslow_unsafe

**Comment by dcousens** [comment]
@fanatid afaik we should be OK to use `allocUnsafe`

**Comment by dcousens** [comment]
Closing in favour of https://github.com/dominictarr/varstruct/pull/13
