### ISSUE TITLE
Alternative short form

### ISSUE THREAD

**Issue by dcousens** [dominictarr/varstruct#14]
Why not

``` js
vstruct({
  x: vstruct.DoubleBE,
  y: vstruct.DoubleBE,
  z: vstruct.DoubleBE
})
```

**Comment by dominictarr** [comment]
that is what it originally was! https://github.com/dominictarr/varstruct/issues/6

@fanatid trusted the spec more than the implementations

**Comment by dcousens** [comment]
Of course!  No that makes perfect sense,  relying on that ordering does catch you out.
