### ISSUE TITLE
for-in statement

### ISSUE THREAD

**Issue by fanatid** [dominictarr/varstruct#6]
`varstruct` uses `for-in` loops, but order of enumerating the properties is not deterministic. [ecma-262 sec. 12.6.4](http://www.ecma-international.org/ecma-262/5.1/#sec-12.6.4)
I think that array of object will be good:
```js
var vector = vstruct([
  { name: 'x', codec: vstruct.DoubleBE },
  { name: 'y', codec: vstruct.DoubleBE },
  { name: 'z', codec: vstruct.DoubleBE }
])
```
Do you accept PR with this changes?

**Comment by mappum** [comment]
:+1: I've been wanting this as well (although thankfully I haven't seen property ordering break anywhere yet).

Bikeshed: maybe `type` would be a better name than `codec`.

**Comment by fanatid** [comment]
@mappum one of the way, how you can break `varstruct`:
```js
var vstruct = require('varstruct')

var obj = {
  x: vstruct.DoubleBE,
  y: vstruct.DoubleBE,
  z: vstruct.DoubleBE
}

//create a vector codec.
var vector = vstruct(obj)

var buffer = vector.encode({
  x: 93.1, y: 87.3, z: 10.39
})

obj.e = vstruct.UInt8

var v = vector.decode(buffer) // undefined
```

**Comment by dominictarr** [comment]
That is just the spec. All the main implementations _are ordered_.
v8 and spidermonkey at least. I'm not sure about chakra (microsoft).

@fanatid can you post that as another issue?

**Comment by dominictarr** [comment]
@fanatid if it the PR was backwards compatible (so it accepted both ways, then i'd merge)

**Comment by fanatid** [comment]
> All the main implementations are ordered.

But it doesn't means that they always been ordered, because standard say nothing about order. Using object may be nice if you looking beauty, but using `varstruct` for protocols in this way is very very bad thing.

Accepting array and object gives misunderstanding. Why you want backwards compatible here? As I see from npm most downloads of `varstruct` gives `bitcoin-protocol`.

What you think about using ES6 and compile to ES5 with babel?

**Comment by fanatid** [comment]
fixed in https://github.com/dominictarr/varstruct/pull/8
